In [1]:
import pandas as pd
import numpy as np

Split Data

In [2]:
#Ambil data csv dan bagi data ke feature & target
data = pd.read_csv ('PhishingData.csv')
feature = data.iloc[:,0:8]
target = data.iloc[:,9]

In [3]:
#split data ke feature_train, feature_test, target_train, target_test
from sklearn.model_selection import train_test_split
feature_train,feature_test,target_train,target_test = train_test_split(feature,target,test_size=0.3)

Multi Layer Perceptron
Parameter: solver='adam' vs solver='sgd'

In [4]:
from sklearn.neural_network import MLPClassifier
nn=MLPClassifier(max_iter=1000000, learning_rate_init=0.001)
nn.fit(feature_train,target_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [5]:
#target test MLP solver='adam'
target_pred = nn.predict(feature_test)
for x,y in zip(target_test,target_pred):
    print("target_test= "+str(x)+" & target_pred= "+str(y))

target_test= 1 & target_pred= 1
target_test= -1 & target_pred= -1
target_test= -1 & target_pred= -1
target_test= -1 & target_pred= -1
target_test= 0 & target_pred= 1
target_test= -1 & target_pred= -1
target_test= 1 & target_pred= 1
target_test= -1 & target_pred= -1
target_test= 0 & target_pred= 0
target_test= -1 & target_pred= -1
target_test= 1 & target_pred= 1
target_test= 1 & target_pred= 1
target_test= 1 & target_pred= 1
target_test= 1 & target_pred= 1
target_test= 1 & target_pred= 1
target_test= 1 & target_pred= 1
target_test= -1 & target_pred= -1
target_test= 1 & target_pred= 1
target_test= 1 & target_pred= 0
target_test= -1 & target_pred= 1
target_test= -1 & target_pred= -1
target_test= -1 & target_pred= -1
target_test= 1 & target_pred= 1
target_test= -1 & target_pred= -1
target_test= 1 & target_pred= -1
target_test= 1 & target_pred= 1
target_test= -1 & target_pred= -1
target_test= -1 & target_pred= -1
target_test= -1 & target_pred= -1
target_test= -1 & target_pred= 1
target_test

In [6]:
#target training pred MLP
target_pred_train = nn.predict(feature_train)

In [7]:
nnn=MLPClassifier(max_iter=1000000, learning_rate_init=0.001, solver='sgd')
nnn.fit(feature_train,target_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='sgd', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [8]:
targetn_pred = nnn.predict(feature_test)
for x,y in zip(target_test,targetn_pred):
    print("target_test= "+str(x)+" & targetn_pred= "+str(y))

target_test= 1 & targetn_pred= 1
target_test= -1 & targetn_pred= -1
target_test= -1 & targetn_pred= -1
target_test= -1 & targetn_pred= -1
target_test= 0 & targetn_pred= -1
target_test= -1 & targetn_pred= -1
target_test= 1 & targetn_pred= 1
target_test= -1 & targetn_pred= -1
target_test= 0 & targetn_pred= -1
target_test= -1 & targetn_pred= -1
target_test= 1 & targetn_pred= 1
target_test= 1 & targetn_pred= 1
target_test= 1 & targetn_pred= 1
target_test= 1 & targetn_pred= 1
target_test= 1 & targetn_pred= 1
target_test= 1 & targetn_pred= 0
target_test= -1 & targetn_pred= -1
target_test= 1 & targetn_pred= 1
target_test= 1 & targetn_pred= 1
target_test= -1 & targetn_pred= 1
target_test= -1 & targetn_pred= -1
target_test= -1 & targetn_pred= -1
target_test= 1 & targetn_pred= 1
target_test= -1 & targetn_pred= -1
target_test= 1 & targetn_pred= 1
target_test= 1 & targetn_pred= 1
target_test= -1 & targetn_pred= -1
target_test= -1 & targetn_pred= -1
target_test= -1 & targetn_pred= -1
target_test= -

In [9]:
targetn_pred_train = nnn.predict(feature_train)

MLP Klasifikasi Report

In [10]:
from sklearn.metrics import classification_report
print(classification_report(target_test,target_pred))

             precision    recall  f1-score   support

         -1       0.90      0.90      0.90       203
          0       0.70      0.70      0.70        27
          1       0.87      0.88      0.87       176

avg / total       0.87      0.87      0.87       406



In [11]:
print(classification_report(target_train,target_pred_train))

             precision    recall  f1-score   support

         -1       0.97      0.97      0.97       499
          0       0.91      0.96      0.94        75
          1       0.96      0.95      0.95       372

avg / total       0.96      0.96      0.96       946



In [12]:
print(classification_report(target_test,targetn_pred))

             precision    recall  f1-score   support

         -1       0.84      0.88      0.86       203
          0       0.43      0.11      0.18        27
          1       0.82      0.88      0.85       176

avg / total       0.81      0.83      0.81       406



In [13]:
print(classification_report(target_train,targetn_pred_train))

             precision    recall  f1-score   support

         -1       0.89      0.94      0.91       499
          0       0.61      0.23      0.33        75
          1       0.85      0.88      0.86       372

avg / total       0.85      0.86      0.85       946



Naive Bayes : Gaussian vs Bernoulli

In [14]:
from sklearn.naive_bayes import GaussianNB
modelnb = GaussianNB()
nbtrain = modelnb.fit(feature_train,target_train)

In [15]:
targetNB_pred = nbtrain.predict(feature_test)
targetNB_pred

array([ 1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  0, -1,
        1,  1,  1, -1, -1,  1, -1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  0,
        1,  1, -1,  1,  1,  1, -1, -1,  1, -1, -1, -1,  1, -1, -1,  1,  0,
        1,  1,  1,  1, -1,  1,  1, -1, -1,  1,  1,  1,  1,  1,  0, -1,  1,
       -1,  1, -1, -1, -1, -1, -1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1,
       -1,  1,  1, -1,  1, -1,  1, -1, -1,  1,  1,  1, -1, -1,  0, -1,  1,
       -1, -1, -1,  1, -1, -1,  1, -1,  1,  1, -1, -1, -1,  0, -1, -1, -1,
       -1, -1,  1, -1,  1, -1,  1, -1, -1, -1,  1,  1, -1, -1,  1,  1,  1,
       -1,  1,  1, -1, -1, -1,  1, -1, -1,  1,  1, -1, -1, -1,  1,  1, -1,
       -1,  1, -1, -1, -1, -1,  1, -1, -1,  1, -1, -1,  1, -1, -1, -1, -1,
        1, -1,  1, -1,  1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1, -1,
        1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1, -1, -1,  1,  1,
        1, -1, -1, -1,  1,  1,  1, -1, -1,  1,  1, -1,  1, -1, -1,  1, -1,
        1, -1,  1,  1, -1

In [16]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, targetNB_pred)

array([[173,   3,  27],
       [ 13,   4,  10],
       [ 20,   5, 151]], dtype=int64)

In [17]:
targetNB_pred_train = nbtrain.predict(feature_train)

In [18]:
confusion_matrix(target_train, targetNB_pred_train)

array([[447,  10,  42],
       [ 29,  17,  29],
       [ 40,  13, 319]], dtype=int64)

In [19]:
from sklearn.naive_bayes import BernoulliNB
modelnbnb = BernoulliNB()
mnbtrain = modelnbnb.fit(feature_train,target_train)

In [20]:
targetBNB_pred = mnbtrain.predict(feature_test)
targetBNB_pred

array([ 1, -1, -1, -1,  1, -1,  1, -1, -1, -1,  1,  1,  1,  1, -1, -1, -1,
        1,  1, -1, -1, -1, -1, -1,  1,  1, -1, -1, -1,  1,  0,  1,  1, -1,
        1, -1, -1,  1,  1,  1, -1, -1,  1,  0, -1, -1,  1, -1, -1,  1,  1,
        1, -1,  1,  1, -1,  1,  1, -1, -1,  1,  1,  1,  1,  1, -1, -1,  1,
       -1,  1, -1, -1, -1, -1, -1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1,
       -1, -1,  1, -1,  1, -1,  1, -1, -1,  1, -1,  1, -1, -1, -1, -1,  1,
       -1,  1, -1,  1, -1,  1,  0, -1,  1,  1, -1, -1, -1,  0, -1, -1,  1,
       -1, -1,  1, -1,  1, -1,  1, -1, -1, -1,  1,  1, -1,  1,  1,  1,  1,
       -1,  1,  1, -1, -1, -1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1, -1,
       -1,  1, -1, -1, -1, -1,  1, -1, -1,  1, -1, -1,  1, -1, -1, -1, -1,
        1, -1,  1, -1,  1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1, -1,
        1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1, -1, -1,  1,  1,
        1, -1, -1, -1,  1,  1,  1, -1, -1,  0,  1, -1,  1, -1, -1,  1, -1,
        1, -1,  1,  1, -1

In [21]:
confusion_matrix(target_test, targetBNB_pred)

array([[177,   2,  24],
       [ 10,   5,  12],
       [ 26,   2, 148]], dtype=int64)

In [22]:
targetBNB_pred_train = mnbtrain.predict(feature_train)

In [23]:
confusion_matrix(target_train, targetBNB_pred_train)

array([[452,  10,  37],
       [ 35,   6,  34],
       [ 39,   8, 325]], dtype=int64)

Naive Bayes Report

In [24]:
print(classification_report(target_test,targetNB_pred))

             precision    recall  f1-score   support

         -1       0.84      0.85      0.85       203
          0       0.33      0.15      0.21        27
          1       0.80      0.86      0.83       176

avg / total       0.79      0.81      0.80       406



In [25]:
print(classification_report(target_train,targetNB_pred_train))

             precision    recall  f1-score   support

         -1       0.87      0.90      0.88       499
          0       0.42      0.23      0.30        75
          1       0.82      0.86      0.84       372

avg / total       0.81      0.83      0.82       946



In [26]:
print(classification_report(target_test,targetBNB_pred))

             precision    recall  f1-score   support

         -1       0.83      0.87      0.85       203
          0       0.56      0.19      0.28        27
          1       0.80      0.84      0.82       176

avg / total       0.80      0.81      0.80       406



In [27]:
print(classification_report(target_train,targetBNB_pred_train))

             precision    recall  f1-score   support

         -1       0.86      0.91      0.88       499
          0       0.25      0.08      0.12        75
          1       0.82      0.87      0.85       372

avg / total       0.80      0.83      0.81       946



KNN : n_neighbors=3 vs n_neigbors=5

In [28]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)

In [29]:
modelknn = model.fit(feature_train,target_train)
predicted = modelknn.predict(feature_test)
print(predicted)

[ 1 -1 -1  1  0 -1  1 -1  0 -1  1  1  1 -1  1  1 -1  1  0  1 -1 -1  1 -1
 -1  1 -1 -1 -1  1 -1 -1  1  1  1  1  1  1  1  1  0 -1  1  1 -1 -1  1  0
  0  1  1  1 -1  1  1 -1  1  1 -1 -1  1  1  1 -1  1  0 -1  1 -1  0  1 -1
 -1 -1 -1  1  1 -1  1  1 -1  1  1  1 -1 -1  1  1 -1  1  0  1  1 -1  1  1
  1 -1 -1 -1 -1  1 -1  1  0  1 -1 -1 -1 -1  1  1 -1  0 -1  0 -1 -1 -1 -1
 -1  1 -1  1  1 -1 -1 -1 -1  1  1 -1  1  1  1  0 -1  1  1 -1 -1 -1 -1  1
  0 -1  1 -1 -1 -1  1  1 -1  1  1 -1 -1 -1 -1  1 -1 -1  1  1 -1  1 -1 -1
  0  1  1 -1  1 -1  1 -1 -1  1  1 -1  1 -1  1  1  1 -1  0  1  1  1  1 -1
  0  0  1  1 -1 -1 -1  1  0  1  0  1  1 -1 -1 -1  1  1  1 -1 -1  0  1 -1
  1 -1 -1  1 -1  1  1  1  1 -1 -1  0 -1  1  0 -1  1 -1 -1  1  1  1  1  1
  1  1  1 -1 -1 -1  0 -1  1 -1 -1  1  1  1  1 -1 -1  1  0  1  1 -1  1 -1
  1  0 -1 -1  1  1 -1  1  1  1  1 -1 -1  1 -1  1 -1  1  1  0  1 -1  1 -1
  0  1  1  1 -1  1  1 -1 -1 -1 -1  1 -1 -1  1  1  1 -1  1 -1  0  1 -1 -1
 -1 -1 -1  0 -1 -1 -1  0 -1 -1  1 -1 -1 -1  1  1  0

In [30]:
predicted_train = modelknn.predict(feature_train)
print(predicted_train)

[ 1  1 -1 -1  0 -1  0 -1  1 -1 -1  1 -1  1 -1 -1  1  1  1 -1  1 -1  1 -1
  1  1  0 -1  0 -1  1 -1  1 -1  1  1  1  1 -1 -1  1  1  1  1  1  1 -1 -1
 -1 -1  1  1 -1 -1 -1 -1 -1  0  1  1 -1 -1  1 -1  1 -1  1 -1  0 -1  1  1
 -1  1 -1 -1  1 -1 -1 -1 -1  1 -1  1 -1  0  1 -1  1  1 -1  1  1  1 -1  1
 -1 -1  1  1  1  0 -1 -1 -1 -1  1  1  0 -1 -1 -1 -1  1 -1  1 -1  1  1 -1
 -1 -1 -1  0 -1 -1  1 -1  1  1  1  1 -1 -1 -1  1 -1  1 -1 -1  1  1  1 -1
  0  1  1 -1 -1 -1 -1  1 -1 -1  0 -1  1 -1 -1  1 -1 -1 -1 -1  1  1  1  1
 -1  1 -1 -1 -1 -1 -1 -1 -1  0  1  1 -1 -1 -1 -1  0  0  1 -1 -1 -1  1 -1
 -1 -1  1 -1  1 -1  1  1  1  1  0 -1 -1  0  1 -1 -1 -1  1 -1 -1 -1  1 -1
  1 -1 -1  1 -1  1  0 -1  1  1  1  1 -1  0  1 -1 -1  1 -1  1 -1  1 -1 -1
  0  1 -1 -1 -1 -1 -1  1  1  1 -1 -1  1  1 -1  1 -1 -1  0 -1 -1  1  1 -1
  1  1  1 -1 -1  1 -1 -1  0 -1  1  0  1 -1 -1 -1 -1  1  1  1  1 -1 -1  1
  1 -1  1 -1  1  0 -1 -1 -1 -1  1 -1  1  0 -1  1 -1  1  1  1  0 -1 -1  1
  1  1 -1 -1  1 -1  0  1  1  0 -1  0 -1 -1 -1  0 -1

In [31]:
modell = KNeighborsClassifier(n_neighbors=5)
modelknn5 = modell.fit(feature_train,target_train)
predicted5 = modelknn5.predict(feature_test)
print(predicted5)

[ 1 -1 -1 -1  0 -1  1 -1  0 -1  1  1  1  1  1  1 -1  1  0  1 -1 -1  1 -1
 -1  1 -1 -1 -1  1  1 -1  1 -1  1  1  1  1  1  1 -1 -1  1  1 -1 -1  1  0
 -1  1  1  1 -1  1  1 -1  1  1 -1 -1  1  1  1  1  1 -1 -1  1 -1  0  1 -1
 -1 -1 -1  1  1 -1  1  1 -1  1  1  1 -1 -1  1  1 -1  1  0  1  1 -1  1  1
  1 -1 -1 -1 -1  1 -1  1  0  1 -1 -1 -1 -1  1  1 -1  0 -1  0 -1 -1 -1 -1
  1  1 -1  1 -1 -1 -1 -1 -1  1  1 -1  1  1  1  0 -1  1  1 -1 -1 -1 -1  1
  0  1  1 -1 -1 -1  1  1 -1  1  1 -1 -1 -1 -1  1 -1 -1  1  1 -1  1 -1 -1
  0 -1  1 -1  1 -1  1 -1 -1  1  1 -1  1 -1  1  1  1 -1  0  1  1  1  1 -1
  0  1  1  1 -1 -1 -1  1  0 -1  1  1  1 -1 -1 -1  1  1  1 -1 -1  1  1 -1
  1 -1 -1  1 -1  1 -1  1  1 -1 -1  0 -1  1  0 -1  1 -1 -1  1  1  1  1  1
  1  1  1 -1 -1 -1  0 -1  1 -1 -1  1  1  1  1 -1 -1  1  1  1  1 -1  1 -1
  1  0  1 -1  1  1 -1  1  1  1  1 -1 -1  1 -1  1 -1  1  1  0  1 -1  1 -1
  0  1  1  1 -1  1  1 -1 -1 -1 -1  1 -1  1 -1  1  1 -1  1 -1  1  1 -1 -1
 -1 -1 -1 -1 -1 -1 -1  0 -1 -1  1 -1 -1 -1  1  1  1

In [32]:
predicted5_train = modelknn5.predict(feature_train)
print(predicted5_train)

[ 1  1 -1 -1  0 -1  0 -1  1 -1 -1  1 -1  1 -1 -1  1  1  1 -1  1 -1  1 -1
  1  1  0 -1  0 -1  1 -1  1 -1  0 -1  1  1 -1 -1  1  1  0 -1  1  1 -1 -1
 -1 -1  1  0 -1 -1 -1 -1 -1  0  1  1 -1 -1  1 -1  1 -1  1 -1  0 -1  1  1
 -1  1 -1 -1  1 -1 -1 -1 -1  1 -1  1 -1  0  1 -1  1  1 -1  1  1  1 -1  1
 -1 -1 -1  1  1  0 -1 -1 -1 -1  1  1  0 -1 -1 -1 -1  1 -1  1 -1  1  1 -1
 -1 -1 -1  0 -1 -1  1 -1  1  1  1  1 -1 -1 -1  1 -1  1 -1 -1  1  1  1 -1
  0  1 -1 -1 -1 -1 -1  1 -1 -1  0 -1  1 -1 -1  1 -1 -1 -1 -1  1  1  1  1
 -1  1 -1 -1 -1 -1 -1 -1 -1  0 -1  1 -1 -1 -1 -1  0  1  1 -1 -1 -1  1 -1
 -1 -1  1 -1  0 -1  1  1  1  1  0 -1 -1  0  1 -1 -1 -1  1 -1 -1 -1  1  0
  1 -1 -1  1 -1  1  0 -1  1  1 -1  1 -1  0  1 -1 -1  1 -1  1 -1  1  1 -1
  0  1 -1 -1 -1 -1 -1  1  1  1 -1 -1  1  1 -1  1 -1 -1  0 -1 -1 -1  1 -1
  1  1  1  1  0  1 -1 -1 -1 -1  1  0  1 -1 -1 -1 -1  1  1  1  1 -1 -1  1
  1 -1  1 -1  1  0 -1 -1 -1 -1  1 -1  1  0 -1  1 -1  1  1  1  0 -1 -1  1
  1  1 -1 -1  1 -1  0  1  1  1 -1 -1 -1 -1 -1  0  1

KNN Klasifikasi Report

In [33]:
print(classification_report(target_test,predicted))

             precision    recall  f1-score   support

         -1       0.90      0.82      0.86       203
          0       0.54      0.78      0.64        27
          1       0.84      0.86      0.85       176

avg / total       0.85      0.83      0.84       406



In [34]:
print(classification_report(target_train,predicted_train))

             precision    recall  f1-score   support

         -1       0.97      0.94      0.95       499
          0       0.87      0.89      0.88        75
          1       0.92      0.95      0.94       372

avg / total       0.94      0.94      0.94       946



In [35]:
print(classification_report(target_train,predicted5_train))

             precision    recall  f1-score   support

         -1       0.95      0.94      0.94       499
          0       0.85      0.84      0.85        75
          1       0.92      0.93      0.92       372

avg / total       0.93      0.93      0.93       946



In [36]:
print(classification_report(target_test,predicted5))

             precision    recall  f1-score   support

         -1       0.91      0.84      0.87       203
          0       0.63      0.63      0.63        27
          1       0.83      0.91      0.87       176

avg / total       0.86      0.85      0.85       406

